version: '3.8'

services:
  microservice1:
    build:
      context: ./dockerfile1
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    networks:
      - net1
    depends_on:
      - db1

  db1:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    networks:
      - net1

  microservice2:
    build:
      context: ./dockerfile2
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    networks:
      - net2
    depends_on:
      - db2

  db2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password2
      MYSQL_DATABASE: db2
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    networks:
      - net2

  microservice3:
    build:
      context: ./dockerfile3
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    networks:
      - net3
    depends_on:
      - db3

  db3:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    networks:
      - net3

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - net1
      - net2
      - net3

networks:
  net1:
  net2:
  net3:
